# -*- coding: utf-8 -*-
"""customer_behaviour_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OPQA-HHe-nzBffTYu7rpJTgZ9Wf_Enj6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df=pd.read_csv("/content/sample_data/ecommerce_customer_data.csv")
df

"""Lets do the explorotary data analysis

"""

df.isnull().sum()

df.duplicated().sum()

"""we are checking whether the data contains any null values from the above code we can infer that there is no null values in the data"""

df1=df['Device_Type'].value_counts()
df1=pd.DataFrame({'device type':df1.index,"count":df1.values})
sns.barplot(x='device type',y='count',data=df1,hue='device type')
plt.show()

"""analysis 1: from the above graph we can infer that most of the customers used mobile for their purchase followed by tablet and desktop

lets create a new column called uplaced_orders which is calculated from the items added to the cart to total_purchases from the items
"""

df['unplaced_rders']=df['Items_Added_to_Cart']-df['Total_Purchases']
df

dfmale=df['Gender'].value_counts()
dfmale=pd.DataFrame({'gender':dfmale.index,'count':dfmale.values})
plt.figure(figsize=(10,3))
plt.pie(dfmale['count'],labels=dfmale['gender'],autopct="%.2f%%")
plt.show()

"""most of the purchases has been done by male customers compared to female customers

Geographic analysis
"""

df_geo=df['Location'].value_counts()
df_geo=pd.DataFrame({'location':df_geo.index,'counts':df_geo.values})
df_geo
plt.figure(figsize=(10,2))
sns.barplot(x='location',y='counts',data=df_geo,hue='location')
plt.title('highest purchases by location')
plt.xlabel('location')
plt.ylabel('total visit')

"""so from the above graph we can infer that kolkata city has the highest purchase compared to other cities"""

df.describe()

"""lets check which age people purchased the most of the products"""

bins=np.linspace(df['Age'].min(),df['Age'].max(),3)
bins

plt.hist(x=df['Age'],bins=bins)
plt.show()

"""from the above graph people we can infer that age group between 18-26 has bought most of the products"""

plt.scatter(df['Product_Browsing_Time'],df['Total_Purchases'],color='b')
plt.show()

"""we have plotted the scatter plot to check the relationship between product browsing time and total_purchases so the graph is kind of vague which neither postively related nor negatively related which is pretty constant through out"""

dff=df.select_dtypes(include='number')
dff1=dff.corr()
sns.heatmap(dff1,annot=True,fmt='.2f')
plt.show()

"""from the above heatmap you can infer that correlation value between items addedd to unplaced orders is 0.88 which is high postive correlation it means more the items added to cart more the unplaced orders"""

df['clv']=(df['Total_Purchases']*df['Total_Pages_Viewed'])/df['Age']
df

"""lets segment the customers based on the purchase count as low medium and high value customers"""

da=np.linspace(df['clv'].min(),df['clv'].max(),4)
da

df['segment']=pd.cut(df['clv'],bins=da,labels=['low','medium','high'])
df

seg=df['segment'].value_counts()
seg=pd.DataFrame({'segment':seg.index,'count':seg.values})
seg
sns.barplot(x='segment',y='count',data=seg,hue='segment')
plt.show()

"""from the above graph we can infer that low value customers are quite high than medium and high value customers we have to focus on high value customers my giving discounts and promotions"""