# -*- coding: utf-8 -*-
"""flipkart_review_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/168rsF0YiQxlLDyzKaaQZ6FAcD-Hp6z_c
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
from nltk.sentiment.vader import SentimentIntensityAnalyzer

df=pd.read_csv("/content/sample_data/flipkart_datas.csv")
df

#EDA

df.isnull().sum()
df.dropna(inplace=True)

df.isnull().sum()

df.shape

df.info()

df.describe()

df['Rate'].value_counts()

import nltk
nltk.download('vader_lexicon')
sent=SentimentIntensityAnalyzer()

df['Positive']=[sent.polarity_scores(i)['pos'] for i in  df['Review']]
df['Negative']=[sent.polarity_scores(i)['neg'] for i in  df['Review']]
df['Neutral']=[sent.polarity_scores(i)['neu'] for i in  df['Review']]

df