# -*- coding: utf-8 -*-
"""t20_world_cup_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KKQofKGwKjM9VQjXQ88XSxk5Oqjrj2zo
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go

df=pd.read_csv("/content/sample_data/t20-world-cup-22.csv")
df

df_winner=df['winner'].value_counts()
df_winner
df_winner=pd.DataFrame({"winner":df_winner.index,"matches":df_winner.values})
df_winner
plt.figure(figsize=(20,6))
sns.barplot(x='winner',y='matches',data=df_winner,hue='winner')
plt.title("no of won matches by country")
plt.show()

df_by=df['won by'].value_counts()
df_by=pd.DataFrame({'won by':df_by.index,'count':df_by.values})
df_by
plt.pie(df_by['count'],labels=df_by['won by'],autopct="%.2f%%")
plt.show()

df_top_runs=df.groupby('top scorer',as_index=False)['highest score'].sum()
df_top_runs=df_top_runs.sort_values(by='highest score',ascending=False)
df_top_runs
plt.figure(figsize=(40,10))
sns.barplot(x='top scorer',y='highest score',data=df_top_runs,hue='top scorer')
plt.show()

df_comp=df.groupby('venue',as_index=False).aggregate({'first innings score':'sum','second innings score':"sum"})
df_comp

fig=go.Figure()
fig.add_trace(go.Bar(x=df_comp['venue'],y=df_comp['first innings score'],name='first innings score'))
fig.add_trace(go.Bar(x=df_comp['venue'],y=df_comp['second innings score'],name='second innings score'))
fig.show()